"""Public API for the software-architecture audit."""

from .audit import audit, audit_report
from .cli import main, parse_args, render_json, render_text, should_fail
from .discovery import (
    artifact_class,
    count_lines,
    git_repository_root,
    is_output_directory_source,
    is_source_bearing,
    iter_audited_files,
    matches_any,
    normalized_leaf,
    semantic_tokens,
    semantic_words,
    split_semantic_words,
)
from .exceptions import (
    exception_path_is_overbroad,
    exception_quality_error,
    load_exceptions,
    load_syntax_rules,
    load_test_source_roots,
)
from .findings import directory_findings, filename_findings, package_manager_findings
from .git_suppressions import git_suppression_findings
from .inline_tests import inline_test_findings, is_test_source
from .records import (
    AnalyzerStatus,
    ArtifactException,
    AuditReport,
    Finding,
    NamingException,
    SyntaxRule,
    TestSourceRoot,
)
from .rules import *
from .suppressions import suppression_findings

__all__ = [
    "ARCHITECTURE_EXTENSIONS",
    "ARTIFACT_EXCEPTION_CLASSES",
    "CATEGORY_CHAIN",
    "DEFAULT_IGNORED_DIRS",
    "FLAT_CLUSTER_LIMIT",
    "GENERATED_HEADER",
    "GENERATED_NAME_PATTERNS",
    "GENERIC_BUCKETS",
    "GENERIC_FILENAMES",
    "GO_ARCH_MARKERS",
    "GO_OS_MARKERS",
    "HARD_LINE_THRESHOLD",
    "JS_LOCKFILES",
    "KOTLIN_PLATFORM_MARKERS",
    "LOW_QUALITY_EXCEPTION_VALUES",
    "MICROFILE_MAX_LINES",
    "MICROFILE_MIN_SIBLINGS",
    "NAMING_EXCEPTION_RULES",
    "PROCEDURAL_PHASES",
    "RESERVED_FILES",
    "RESERVED_PATTERNS",
    "SEVERITY_RANK",
    "SOFT_LINE_THRESHOLD",
    "SOURCE_BEARING_CONFIG_EXTENSIONS",
    "SOURCE_BEARING_DIRECTORIES",
    "SOURCE_BEARING_IDL_EXTENSIONS",
    "SOURCE_EXTENSIONS",
    "STRONG_LINE_THRESHOLD",
    "STRUCTURAL_DIRECTORIES",
    "TEMPORAL_OR_NUMBERED",
    "AnalyzerStatus",
    "ArtifactException",
    "AuditReport",
    "Finding",
    "NamingException",
    "SyntaxRule",
    "TestSourceRoot",
    "artifact_class",
    "audit",
    "audit_report",
    "count_lines",
    "directory_findings",
    "exception_path_is_overbroad",
    "exception_quality_error",
    "filename_findings",
    "git_repository_root",
    "git_suppression_findings",
    "inline_test_findings",
    "is_output_directory_source",
    "is_source_bearing",
    "is_test_source",
    "iter_audited_files",
    "load_exceptions",
    "load_syntax_rules",
    "load_test_source_roots",
    "main",
    "matches_any",
    "normalized_leaf",
    "package_manager_findings",
    "parse_args",
    "render_json",
    "render_text",
    "semantic_tokens",
    "semantic_words",
    "should_fail",
    "split_semantic_words",
    "suppression_findings",
]
