group=__GROUP__
version=0.1.0

kotlinVersion=__KOTLIN_VERSION__
intellijPlatformGradlePluginVersion=__INTELLIJ_PLATFORM_GRADLE_PLUGIN_VERSION__
platformType=IC
platformVersion=__PLATFORM_VERSION__
pluginId=__PLUGIN_ID__
pluginName=__PLUGIN_NAME__
pluginSinceBuild=__SINCE_BUILD__
pluginUntilBuild=__UNTIL_BUILD__

org.gradle.configuration-cache=true
org.gradle.caching=true
kotlin.stdlib.default.dependency=false
