"""Public API for the software-architecture audit."""

from .audit import audit, audit_report
from .cli import main, parse_args, render_json, render_text, should_fail
from .discovery import (
    artifact_class,
    count_lines,
    iter_audited_files,
    matches_any,
    normalized_leaf,
    semantic_tokens,
    semantic_words,
    split_semantic_words,
)
from .exceptions import (
    apply_exceptions,
    exception_path_is_overbroad,
    exception_quality_error,
    load_exceptions,
    load_syntax_rules,
)
from .findings import directory_findings, filename_findings, package_manager_findings
from .records import (
    AnalyzerStatus,
    ArtifactException,
    AuditReport,
    Finding,
    NamingException,
    SyntaxRule,
)
from .rules import *

__all__ = [
    "ARCHITECTURE_EXTENSIONS",
    "ARTIFACT_EXCEPTION_CLASSES",
    "CATEGORY_CHAIN",
    "DEFAULT_IGNORED_DIRS",
    "FAIL_RANK",
    "GENERATED_HEADER",
    "GENERATED_NAME_PATTERNS",
    "GENERIC_BUCKETS",
    "GENERIC_FILENAMES",
    "GO_ARCH_MARKERS",
    "GO_OS_MARKERS",
    "JS_LOCKFILES",
    "KOTLIN_PLATFORM_MARKERS",
    "LOW_QUALITY_EXCEPTION_VALUES",
    "NAMING_EXCEPTION_RULES",
    "RESERVED_FILES",
    "RESERVED_PATTERNS",
    "SEVERITY_RANK",
    "SOURCE_EXTENSIONS",
    "STRUCTURAL_DIRECTORIES",
    "TEMPORAL_OR_NUMBERED",
    "AnalyzerStatus",
    "ArtifactException",
    "AuditReport",
    "Finding",
    "NamingException",
    "SyntaxRule",
    "apply_exceptions",
    "artifact_class",
    "audit",
    "audit_report",
    "count_lines",
    "directory_findings",
    "exception_path_is_overbroad",
    "exception_quality_error",
    "filename_findings",
    "iter_audited_files",
    "load_exceptions",
    "load_syntax_rules",
    "main",
    "matches_any",
    "normalized_leaf",
    "package_manager_findings",
    "parse_args",
    "render_json",
    "render_text",
    "semantic_tokens",
    "semantic_words",
    "should_fail",
    "split_semantic_words",
]
