"""Shared audit rules and classifications."""

from __future__ import annotations

import re

SOURCE_EXTENSIONS = {
    ".adb", ".ads", ".asm", ".bas", ".bash", ".c", ".c3", ".cbl", ".cc", ".clj", ".cljs", ".cljc", ".cob", ".cobol", ".cpp", ".cpy", ".cr", ".cs", ".cshtml", ".cjs", ".cts", ".cxx", ".d", ".dart", ".erl", ".escript", ".ex", ".exs", ".f", ".f03", ".f08", ".f77", ".f90", ".f95", ".fish", ".for", ".ftn", ".fs", ".fsi", ".fsx", ".gemspec", ".go", ".groovy", ".h", ".hh", ".hpp", ".hrl", ".hs", ".hxx", ".java", ".jl", ".js", ".jsx", ".kt", ".kts", ".lhs", ".lisp", ".lua", ".m", ".mjs", ".ml", ".mli", ".mm", ".mts", ".nim", ".odin", ".p", ".pas", ".php", ".pl", ".pm", ".pp", ".py", ".ps1", ".pyi", ".pyw", ".r", ".rake", ".rb", ".rs", ".s", ".scala", ".scm", ".sh", ".sol", ".st", ".svelte", ".swift", ".tcl", ".ts", ".tsx", ".v", ".vb", ".vhd", ".vhdl", ".vbs", ".vue", ".zig", ".zsh",
}
ARCHITECTURE_EXTENSIONS = SOURCE_EXTENSIONS | {".adoc", ".avsc", ".capnp", ".cfg", ".conf", ".fbs", ".gql", ".graphql", ".ini", ".json", ".jsonc", ".md", ".proto", ".rst", ".sql", ".thrift", ".toml", ".txt", ".xml", ".yaml", ".yml"}
DEFAULT_IGNORED_DIRS = {".bundle", ".cache", ".dart_tool", ".direnv", ".eggs", ".git", ".gradle", ".hg", ".idea", ".mypy_cache", ".next", ".npm", ".nuget", ".pnpm-store", ".pytest_cache", ".ruff_cache", ".svn", ".swiftpm", ".tox", ".turbo", ".venv", ".vscode", ".yarn", "CMakeFiles", "DerivedData", "Pods", "__pycache__", "artifacts", "bazel-bin", "bazel-out", "bazel-testlogs", "bower_components", "build", "cmake-build-debug", "cmake-build-release", "coverage", "dist", "node_modules", "obj", "out", "reports", "target", "tmp", "venv"}
GENERIC_BUCKETS = {"base", "common", "commons", "core", "helper", "helpers", "manager", "managers", "misc", "model", "models", "service", "services", "shared", "type", "types", "util", "utils"}
GENERIC_FILENAMES = GENERIC_BUCKETS | {"constants", "factory", "functions", "stuff"}
STRUCTURAL_DIRECTORIES = {"app", "apps", "bin", "cmd", "config", "docs", "examples", "include", "lib", "libs", "main", "pkg", "script", "scripts", "src", "source", "test", "tests", "tool", "tools"}
TEMPORAL_OR_NUMBERED = re.compile(r"(?:^|[-_.])(new|old|final|latest|backup|copy|extra|temp|tmp|v\d+|\d+)(?:[-_.]|$)", re.IGNORECASE)
CATEGORY_CHAIN = re.compile(r"(?:base|controller|factory|handler|helper|impl|manager|provider|repository|service|util)(?:[-_](?:base|controller|factory|handler|helper|impl|manager|provider|repository|service|util))+", re.IGNORECASE)
GENERATED_HEADER = re.compile(r"^\s*(?://+|#+|/\*+|\*+)\s*(?:@generated\b|code generated\b.*\bdo not edit\b|generated by\b.*\bdo not edit\b|this file (?:is|was) generated\b)", re.IGNORECASE)
GENERATED_NAME_PATTERNS = ("*.designer.cs", "*.freezed.dart", "*.g.dart", "*.gen.*", "*.generated.*", "*.pb.cc", "*.pb.cpp", "*.pb.go", "*.pb.h", "*.pb.hpp")
ARTIFACT_EXCEPTION_CLASSES = {"fixture", "framework", "generated", "migration", "schema-derived", "snapshot", "vendor"}
RESERVED_FILES = {".architecture-enforcement.json", "agents.md", "build.gradle", "cargo.toml", "changelog.md", "cmakelists.txt", "composer.json", "deno.json", "deno.jsonc", "description", "dockerfile", "gemfile", "makefile", "namespace", "openai.yaml", "package.json", "packages.lock.json", "podfile", "pyproject.toml", "readme.md", "settings.gradle", "settings.xml", "skill.md"}
RESERVED_PATTERNS = ("tsconfig*.json", "*.csproj", "*.fsproj", "*.vbproj", "*.xcodeproj")
GO_OS_MARKERS = {"aix", "android", "darwin", "dragonfly", "freebsd", "illumos", "ios", "js", "linux", "netbsd", "openbsd", "plan9", "solaris", "wasip1", "windows"}
GO_ARCH_MARKERS = {"386", "amd64", "arm", "arm64", "loong64", "mips", "mips64", "mips64le", "mipsle", "ppc64", "ppc64le", "riscv64", "s390x", "wasm"}
KOTLIN_PLATFORM_MARKERS = {"android", "common", "ios", "js", "jvm", "linux", "native", "wasm"}
JS_LOCKFILES = {"bun": ("bun.lock", "bun.lockb"), "npm": ("npm-shrinkwrap.json", "package-lock.json"), "pnpm": ("pnpm-lock.yaml",), "yarn": ("yarn.lock",)}
SEVERITY_RANK = {"error": 0, "warning": 1, "notice": 2}
FAIL_RANK = {"error": 0, "warning": 1, "notice": 2, "never": -1}
NAMING_EXCEPTION_RULES = {"category-chain", "filename-colony", "generic-file", "semantic-token-limit", "redundant-owner-prefix", "temporal-file"}
LOW_QUALITY_EXCEPTION_VALUES = {"", "compatibility", "framework", "legacy", "manual", "n/a", "na", "never", "none", "permanent", "refactor cost", "temporary", "tbd", "todo", "unknown", "x"}
